name: ${pluginName}
main: com.github.igotyou.FactoryMod.FactoryMod
author: Maxopoly, igotyou
version: ${version}
depend: [CivModCore]
softdepend: [NameLayer, Citadel]
description: ${description}
api-version: ${api_version}
permissions:
    fm.public:
        default: true
    fm.op:
        default: op
